  /// \file ConnectorTimingSeedingTool.h
/*
 *
 * ConnectorTimingSeedingTool.h header template automatically generated by a class generator
 * Creation date : mar. d�c. 8 2015
 *
 * This file is part of APRILContent libraries.
 * 
 * APRILContent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * APRILContent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with APRILContent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef CONNECTORTIMINGSEEDINGTOOL_H
#define CONNECTORTIMINGSEEDINGTOOL_H

#include "APRILTools/ConnectorAlgorithmTool.h"

#include <memory>

namespace april_content
{

class CaloHit;
class Connector;

/** 
 * @brief ConnectorTimingSeedingTool class
 */ 
class ConnectorTimingSeedingTool : public ConnectorAlgorithmTool 
{
public:
    /**
     *  @brief  Factory class for instantiating algorithm tool
     */
    class Factory : public pandora::AlgorithmToolFactory
    {
    public:
        pandora::AlgorithmTool *CreateAlgorithmTool() const;
    };

	/**
	 *  @brief  Seed connectors from the calo hit list
	 *
	 *  @param  algorithm the parent algorithm to access pandora content
	 *  @param  pCaloHitList the calo hit list to process
	 */
	pandora::StatusCode Process(const pandora::Algorithm &algorithm, const pandora::CaloHitList *const pCaloHitList = nullptr);

	/**
	 *  @brief  Fill a map with the hits and their correspondign timing layer
	 *
	 *  @param  orderedCaloHitList the original calo hit list
	 *  @param  timeOrderedCaloHitList the time ordered calo hit list
	 */
	pandora::StatusCode PrepareTimeOrderedList(pandora::OrderedCaloHitList& orderedCaloHitList, std::map<const unsigned int, std::unique_ptr<pandora::CaloHitList>>& timeOrderedCaloHitList);


	/**
	 *  @brief  Read settings from the xml handle
	 *
	 *  @param  xmlHandle the xml handle to settings
	 */
	pandora::StatusCode ReadSettings(const pandora::TiXmlHandle xmlHandle);

private:
	float                       m_hitSearchRange;
	float                       m_maxCollectorLength;
	unsigned int                m_hitCollectionToUse;
	float                       m_maxConnectionAngleFine;
	float                       m_maxConnectionAngleCoarse;
	float                       m_maxTransverseDistanceFine;
	float                       m_maxTransverseDistanceCoarse;
	unsigned int                m_maxPseudoLayerConnection;
	bool                        m_connectOnlyAvailable;
	bool                        m_shouldUseIsolatedHits;
	bool                        m_shouldDiscriminateConnectedHits;
	unsigned int                m_connectorCreationStage;
};

//------------------------------------------------------------------------------------------------------------------------------------------

inline pandora::AlgorithmTool *ConnectorTimingSeedingTool::Factory::CreateAlgorithmTool() const
{
	return new ConnectorTimingSeedingTool();
}

} 

#endif  //  CONNECTORTIMINGSEEDINGTOOL_H
