  /// \file ClusterHelper.h
/*
 *
 * ClusterHelper.h header template automatically generated by a class generator
 * Creation date : ven. avr. 10 2015
 *
 * This file is part of ArborContent libraries.
 * 
 * ArborContent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * ArborContent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ArborContent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef CLUSTERHELPER_H
#define CLUSTERHELPER_H

#include "Pandora/PandoraInternal.h"
#include "Pandora/PandoraInputTypes.h"

namespace arbor_content
{

/** 
 *  @brief  ClusterHelper class
 */ 
class ClusterHelper 
{
public:
	/**
	 *
	 */
	static pandora::StatusCode GetCentroid(const pandora::Cluster *const pCluster, pandora::CartesianVector &centroid);

	/**
	 *
	 */
	static pandora::StatusCode GetClosestDistanceApproach(const pandora::Cluster *const pCluster, pandora::CartesianVector &point,
			float &closestDistance);

	/**
	 */
	static pandora::StatusCode GetNCaloHitSeeds(const pandora::Cluster *const pCluster, unsigned int &nSeeds);
}; 

} 

#endif  //  CLUSTERHELPER_H
