/*
 *
 * ReclusterHelper.h header template automatically generated by a class generator
 * Creation date : jeu. avr. 9 2015
 *
 * This file is part of ArborContent libraries.
 * 
 * ArborContent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * ArborContent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ArborContent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef RECLUSTERHELPER_H
#define RECLUSTERHELPER_H

#include "Pandora/PandoraInputTypes.h"
#include "Pandora/PandoraInternal.h"

namespace arbor_content
{

class CaloHit;

/** 
 * @brief ReclusterHelper class
 */ 
class ReclusterHelper 
{
public:
    /**
     *  @brief  Evaluate the compatibility of a cluster with its associated tracks. Reclustering can be used to split up a
     *          cluster and produce more favourable track/cluster matches.
     *
     *  @param  pandora the associated pandora instance
     *  @param  pCluster address of the cluster
     *  @param  trackList address of the list of tracks associated with the cluster
     *  @param  energyResolutionFactory the number of sigmas of resolution in the chi computation
     *
     *  @return the chi value for the suitability of the track/cluster associations
     */
    static float GetTrackClusterCompatibility(const pandora::Pandora &pandora, const pandora::Cluster *const pCluster,
        const pandora::TrackList &trackList, float energyResolutionFactor = 1.f);

    /**
     *  @brief  Evaluate the compatibility of a cluster with its associated tracks. Reclustering can be used to split up a
     *          cluster and produce more favourable track/cluster matches.
     *
     *  @param  pandora the associated pandora instance
     *  @param  clusterEnergy the cluster energy
     *  @param  trackEnergy the sum of the energies of the associated tracks
     *  @param  energyResolutionFactory the number of sigmas of resolution in the chi computation
     *
     *  @return the chi value for the suitability of the track/cluster associations
     */
    static float GetTrackClusterCompatibility(const pandora::Pandora &pandora, const float clusterEnergy, const float trackEnergy,
    		float energyResolutionFactor = 1.f);

    /**
     *  @brief  Create a separated tree cluster from a seed calo hit contained in an original cluster.
     *          Possible only if the original cluster contains more than one tree (more than one seed calo hit).
     *          Calo hits of the newly created tree cluster are removed from the original one
     *
     *  @param  algorithm the algorithm instance used to access pandora content
     *  @param  pSeedCaloHit the seed calo hit pointer to build the separated tree from
     *  @param  pOriginalCluster the original cluster pointer from which to separate the tree
     */
    static pandora::StatusCode SplitTreeFromCluster(const pandora::Algorithm &algorithm, const arbor_content::CaloHit *const pSeedCaloHit,
    		const pandora::Cluster *const pOriginalCluster, const pandora::Cluster *&pSeparatedTreeCluster, const std::string &originalClusterListName = "");

    /**
     *  @brief  Create a cluster list for each tree contained in the cluster
     *          Possible only if the cluster contains more than one tree (more than one seed calo hit)
     *
     *  @param  algorithm the algorithm instance used to access pandora content
     *  @param  pCluster the cluster to split
     *  @param  treeClusterVector the split list of tree clusters
     */
    static pandora::StatusCode SplitClusterIntoTreeClusters(const pandora::Algorithm &algorithm, const pandora::Cluster *const pCluster,
    		pandora::ClusterVector &treeClusterVector);

}; 

} 

#endif  //  RECLUSTERHELPER_H
