  /// \file CompositeAlgorithm.cc
/*
 *
 * CompositeAlgorithm.cc source template automatically generated by a class generator
 * Creation date : mar. nov. 17 2015
 *
 * This file is part of APRILContent libraries.
 * 
 * APRILContent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * APRILContent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with APRILContent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#include "APRILUtility/CompositeAlgorithm.h"

#include "Pandora/AlgorithmHeaders.h"

namespace april_content
{

pandora::StatusCode CompositeAlgorithm::Run()
{
    // Run daughter algorithms
    for (pandora::StringVector::const_iterator iter = m_algorithmList.begin(), iterEnd = m_algorithmList.end(); iter != iterEnd; ++iter)
    {
        PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::RunDaughterAlgorithm(*this, *iter));
    }

	return pandora::STATUS_CODE_SUCCESS;
}

//------------------------------------------------------------------------------------------------------------------------------------------

pandora::StatusCode CompositeAlgorithm::ReadSettings(const pandora::TiXmlHandle xmlHandle)
{
    PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::XmlHelper::ProcessAlgorithmList(*this, xmlHandle, "algorithms",
    		m_algorithmList));

	return pandora::STATUS_CODE_SUCCESS;
}


} 

