IF(NOT DEFINED MLPACK_DIR)
   MESSAGE(STATUS "It is mandorary to sepecify mlpack directory.")
ENDIF()

FIND_PATH(MLPACK_INCLUDE_DIR core.hpp HINTS ${MLPACK_DIR}/include/*)
FIND_LIBRARY(MLPACK_LIBRARY NAMES mlpack HINTS ${MLPACK_DIR}/*)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(mlpack DEFAULT_MSG MLPACK_LIBRARY MLPACK_INCLUDE_DIR)

IF(NOT MLPACK_FOUND)
  MESSAGE(FATAL_ERROR "mlpack not found")
ENDIF()
